Exercise 2
TheConfuZzledDude/DevOps-Course-Starter pull request #2
Opened 2022-09-07 02:01 UTC by TheConfuZzledDude

Please make sure you are raising this PR against your own repository and not the original. If it says https://github.com/CorndelWithSoftwire in the search bar right now, you are in the wrong place!

Please also don't forget to submit the PR's url to Aptem afterwards (by clicking on the corresponding exercise component, pasting the url in the textbox that appears and then pressing the finish button).

2022-09-08 16:09 UTC, CharlieCumber1 requested changes
I have managed to get your code running locally - and all looks functional.

Please can you add instructions to the README regarding the Trello environment variables such that anyone can set up your code locally?

2022-09-08 16:09 UTC, CharlieCumber1 commented on todo_app/data/trello_items.py
> +from flask import session
This import is no longer used.

2022-09-08 16:09 UTC, CharlieCumber1 commented on todo_app/data/trello_items.py
> +    items = get_items()
`get_items()` is not defined, nor is the `items` variable used - this whole line can be deleted.

2022-09-08 16:09 UTC, CharlieCumber commented on todo_app/data/trello_items.py
> +    board_id = os.getenv("TRELLO_BOARD_ID")
This variable is not used within the scope of this function.

2022-09-08 16:09 UTC, CharlieCumber commented on todo_app/data/trello_items.py
> +    response = requests.request("DELETE", url, params=query)
The `response` variable has a value set but is not used.

2022-10-31 14:06 UTC, CorndelWithSoftwireDevOps approved these changes
Looks good to me, just one small suggestion

2022-10-31 14:06 UTC, CorndelWithSoftwireDevOps commented on todo_app/app.py
> +class Item:
Usually, classes go in separate files

2022-11-01 14:24 UTC, merged